### ISSUE TITLE
error in s2s 0.15.0

### ISSUE THREAD

**Issue by kztmk** [cndlhvn/s2s-redux-actions-sample#1]
素晴らしものを公開いただき、ありがとうございます。

s2s 0.15.0 にて　buildersフォルダに、coin.jsを作成しようとしたところ

abel:s2s-redux-actions-root src/actions/coin.js → src/actions/index.js
TEMPLATE templates/redux-action.js → src/actions/coin.js
TypeError: Cannot destructure property `handlerName` of 'undefined' or 'null'.
    at handlePlugin (/Users/inabakazuya/Documents/Devs/ReactLessons/s2s-redux-actions-sample/node_modules/s2s/lib/handlers/handle-plugin.js:44:27)
    at handlePlugins (/Users/inabakazuya/Documents/Devs/ReactLessons/s2s-redux-actions-sample/node_modules/s2s/lib/handlers/index.js:54:40)
    at FSWatcher.watcher.on.input (/Users/inabakazuya/Documents/Devs/ReactLessons/s2s-redux-actions-sample/node_modules/s2s/lib/index.js:79:32)
    at emitOne (events.js:121:20)
    at FSWatcher.emit (events.js:211:7)
    at FSWatcher.<anonymous> (/Users/inabakazuya/Documents/Devs/ReactLessons/s2s-redux-actions-sample/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (/Users/inabakazuya/Documents/Devs/ReactLessons/s2s-redux-actions-sample/node_modules/chokidar/index.js:238:5)
    at FSWatcher.<anonymous> (/Users/inabakazuya/Documents/Devs/ReactLessons/s2s-redux-actions-sample/node_modules/chokidar/lib/fsevents-handler.js:204:14)
    at addOrChange (/Users/inabakazuya/Documents/Devs/ReactLessons/s2s-redux-actions-sample/node_modules/chokidar/lib/fsevents-handler.js:210:7)
    at /Users/inabakazuya/Documents/Devs/ReactLessons/s2s-redux-actions-sample/node_modules/chokidar/lib/fsevents-handler.js:216:35
    at FSReqWrap.oncomplete (fs.js:135:15)

とエラーが発生します。

actions
api
reducers
sagas

には、正常にcoin.jsファイルが作成されますが、reducers/coin.jsの中身は

undefined

の1行のみです。

他は、正常に作成されます。

以上、ご報告になります。

**Comment by cndlhvn** [comment]
s2sのバージョンが上がって、どのハンドラーがファイルの変更を行ったが表示されるようになったと聞いていて、遅かれ早かれこの問題が発生するだろうと思っていました。

最新のs2sのバージョンに対応するよう、やってみます。

**Comment by cndlhvn** [comment]
s2s-handler-babel-object-rest-spread変更しました。s2s-handler-babel-object-rest-spreadのバージョンを0.0.3にアップするとs2s 0.15.0でも使えるようになります。
